
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-python
spec:
  template:
    spec:
      containers:
        - name: hello-python
          image: ghcr.io/aarhustech/hello-python:latest
      restartPolicy: Never