apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-python
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mscn-aarhustech/basic-programming.git
    targetRevision: main
    path: Python/HelloWorldKubernetes/hello-python
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true