apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hello-kubernetes-test
  template:
    metadata:
      labels:
        app: hello-kubernetes-test
    spec:
      containers:
        - name: hello-kubernetes-test
          image: ghcr.io/mscn-aarhustech/hello-kubernetes-test:latest
          imagePullPolicy: IfNotPresent